"use client";

import type { RoadmapItemStatus, RoadmapPhase } from "@/lib/roadmaps";
import { RoadmapItem } from "@/components/roadmap/RoadmapItem";

export function PhaseCard({ phase, expanded, onToggle, onOpenItem, onItemStatus }: { phase: RoadmapPhase; expanded: boolean; onToggle: () => void; onOpenItem: (itemId: string) => void; onItemStatus: (itemId: string, status: RoadmapItemStatus) => void }): JSX.Element {
  const skills = Array.from(new Set(phase.items.map((item) => item.skill_name).filter(Boolean))) as string[];
  const estimatedMinutes = phase.items.reduce((sum, item) => sum + (item.estimated_minutes ?? 0), 0);
  const intervention = phase.phase_metadata?.source === "adaptive_engine";
  const statusStyle = phase.status === "completed" ? "bg-emerald-400/10 text-emerald-300" : phase.status === "active" ? "bg-sky-400/10 text-sky-300" : phase.status === "paused" ? "bg-amber-400/10 text-amber-300" : "bg-slate-800 text-slate-400";
  return <article className={`overflow-hidden rounded-2xl border bg-slate-900/65 transition ${intervention ? "border-orange-400/40 shadow-lg shadow-orange-950/20" : phase.status === "active" ? "border-sky-400/30" : "border-slate-800"} ${phase.status === "locked" ? "opacity-60" : ""}`}>
    <button type="button" onClick={onToggle} className="w-full p-5 text-left sm:p-6" aria-expanded={expanded}>
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className={`text-xs font-bold uppercase tracking-[0.18em] ${intervention ? "text-orange-300" : "text-slate-500"}`}>{intervention ? "Adaptive intervention" : `Phase ${phase.order_index + 1}`}</p><h2 className="mt-2 text-xl font-bold">{phase.title}</h2></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusStyle}`}>{phase.status === "active" ? "In Progress" : phase.status.charAt(0).toUpperCase() + phase.status.slice(1)}</span><span className="text-sm text-slate-500">{phase.estimated_weeks ?? 1} wk</span></div></div>
      <div className="mt-5 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-emerald-400 to-sky-400 transition-all" style={{ width: `${phase.progress_percentage}%` }} /></div><span className="text-xs font-bold text-slate-400">{phase.completed_items_count}/{phase.items_count}</span></div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{skills.slice(0, 3).map((skill) => <span key={skill} className="rounded-full bg-indigo-400/10 px-2.5 py-1 text-xs text-indigo-200">{skill}</span>)}{skills.length > 3 && <span className="text-xs text-slate-500">+{skills.length - 3} more</span>}</div><span className="text-sm font-semibold text-sky-300">{expanded ? "Collapse ↑" : "Expand →"}</span></div>
    </button>
    <div className={`grid transition-[grid-template-rows] duration-300 ${expanded ? "grid-rows-[1fr]" : "grid-rows-[0fr]"}`}><div className="overflow-hidden"><div className="border-t border-slate-800 px-5 pb-6 pt-5 sm:px-6"><p className="leading-7 text-slate-400">{phase.description}</p><div className="mt-4 flex flex-wrap gap-4 text-xs text-slate-500"><span>Estimated study time: {Math.ceil(estimatedMinutes / 60)} hours</span><span>{skills.length} skills covered</span></div><div className="mt-5 space-y-2">{phase.items.map((item) => <RoadmapItem key={item.id} item={item} locked={phase.status === "locked" || phase.status === "paused"} onOpen={() => onOpenItem(item.id)} onStatus={(status) => onItemStatus(item.id, status)} />)}</div>{phase.status === "active" && phase.progress_percentage === 100 && <p className="mt-5 rounded-xl bg-emerald-400/10 p-3 text-sm text-emerald-300">Phase completed — the next phase has been unlocked.</p>}</div></div></div>
  </article>;
}
