"use client";

import { useState, type ReactNode } from "react";

export function TutorLayout({ title, sidebar, contextPanel, children }: { title: string; sidebar: ReactNode; contextPanel: ReactNode; children: ReactNode }): JSX.Element {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [contextOpen, setContextOpen] = useState(false);
  return <div className="-m-4 flex h-[calc(100vh-4rem)] min-h-[620px] overflow-hidden bg-slate-950 sm:-m-6"><div className="hidden w-[260px] shrink-0 border-r border-slate-800 md:block">{sidebar}</div>{sidebarOpen && <div className="fixed inset-0 z-50 md:hidden"><button type="button" aria-label="Close conversations" onClick={() => setSidebarOpen(false)} className="absolute inset-0 bg-slate-950/80" /><div className="relative h-full w-[min(85vw,300px)] border-r border-slate-800 shadow-2xl">{sidebar}</div></div>}<main className="flex min-w-0 flex-1 flex-col"><header className="flex h-14 shrink-0 items-center justify-between border-b border-slate-800 px-4"><div className="flex min-w-0 items-center gap-3"><button type="button" onClick={() => setSidebarOpen(true)} aria-label="Open conversations" className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 md:hidden">☰</button><div className="min-w-0"><p className="truncate text-sm font-bold">{title}</p><p className="text-[11px] text-emerald-400">● AI Tutor online</p></div></div><button type="button" onClick={() => setContextOpen(true)} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs font-semibold text-slate-300 xl:hidden">Context ⓘ</button></header>{children}</main><div className="hidden w-[280px] shrink-0 border-l border-slate-800 xl:block">{contextPanel}</div>{contextOpen && <div className="fixed inset-0 z-50 xl:hidden"><button type="button" aria-label="Close context" onClick={() => setContextOpen(false)} className="absolute inset-0 bg-slate-950/80" /><div className="absolute right-0 h-full w-[min(90vw,340px)] border-l border-slate-800 shadow-2xl">{contextPanel}</div></div>}</div>;
}
