"use client";
import { useEffect,useState } from "react"; import type { CareerReadiness } from "@/lib/career";

const LEVEL_COLORS:Record<string,string>={job_ready:"#10b981",nearly_ready:"#3b82f6",on_track:"#f59e0b",building_foundation:"#f97316",just_starting:"#ef4444"};
const LEVEL_LABELS:Record<string,string>={job_ready:"Job Ready",nearly_ready:"Nearly Ready",on_track:"On Track",building_foundation:"Building Foundation",just_starting:"Just Starting"};

export function CareerReadinessMeter({value,size=220,level,essential,important,compact=false}:{value:number;size?:number;level?:string;essential?:number;important?:number;compact?:boolean}):JSX.Element{
 const [animated,setAnimated]=useState(false);useEffect(()=>{const frame=requestAnimationFrame(()=>setAnimated(true));return()=>cancelAnimationFrame(frame)},[]);
 const normalized=Math.max(0,Math.min(100,value)),radius=42,circumference=2*Math.PI*radius,arc=circumference*.75,color=LEVEL_COLORS[level??""]??(value>=85?"#10b981":value>=70?"#3b82f6":value>=50?"#f59e0b":value>=25?"#f97316":"#ef4444");
 const bars:[[string,number|undefined],[string,number|undefined],[string,number|undefined]]=[["Essential",essential],["Important",important],["Overall",normalized]];
 return <div className={compact?"":"w-full"}><div className="relative mx-auto" style={{width:size,height:size*.86}} aria-label={`${normalized}% ${LEVEL_LABELS[level??""]??"career ready"}`}><svg viewBox="0 0 100 88" className="overflow-visible"><circle cx="50" cy="50" r={radius} fill="none" stroke="#1e293b" strokeWidth="8" strokeLinecap="round" strokeDasharray={`${arc} ${circumference}`} transform="rotate(135 50 50)"/><circle cx="50" cy="50" r={radius} fill="none" stroke={color} strokeWidth="8" strokeLinecap="round" strokeDasharray={`${arc} ${circumference}`} strokeDashoffset={animated?arc*(1-normalized/100):arc} transform="rotate(135 50 50)" className="transition-[stroke-dashoffset] duration-1000 ease-out"/></svg><div className="absolute inset-x-0 top-[31%] text-center"><b className={compact?"text-3xl":"text-5xl"}>{normalized}%</b><p className="mt-1 text-xs font-bold uppercase tracking-wide" style={{color}}>{LEVEL_LABELS[level??""]??"Career Ready"}</p></div></div>{(essential!==undefined||important!==undefined)&&<div className="mx-auto mt-1 max-w-sm space-y-2">{bars.map(([label,number])=>number===undefined?null:<div key={label}><div className="mb-1 flex justify-between text-xs text-slate-400"><span>{label}</span><span>{Math.round(number)}%</span></div><div className="h-1.5 rounded-full bg-slate-800"><div className="h-full rounded-full transition-all duration-700" style={{width:`${number}%`,backgroundColor:color}}/></div></div>)}</div>}</div>
}

export function ReadinessMeterFromData({readiness,size}:{readiness:CareerReadiness;size?:number}):JSX.Element{return <CareerReadinessMeter value={readiness.overall_readiness_percentage} level={readiness.readiness_level} essential={readiness.essential_readiness*100} important={readiness.important_readiness*100} size={size}/>}
