"use client";
import { useEffect,useState } from "react";
import { deleteCareerGoal,getCareerActionPlan,getCareerGoal,getCareerMarketInsights,getCareerReadiness,getCareerRoles,setCareerGoal,type ActionPlan,type CareerGoalBundle,type CareerReadiness,type CareerRole,type MarketInsights } from "@/lib/career";
import { ReadinessMeterFromData } from "./CareerReadinessMeter"; import { GapActionPlan } from "./GapActionPlan"; import { RoleComparison } from "./RoleComparison"; import { RoleSelector } from "./RoleSelector"; import { SkillGapChart } from "./SkillGapChart";

type Tab="goal"|"explore"|"compare";
export function CareerPage():JSX.Element{
 const [roles,setRoles]=useState<CareerRole[]>([]),[readiness,setReadiness]=useState<Record<string,CareerReadiness>>({}),[goal,setGoal]=useState<CareerGoalBundle|null>(null),[plan,setPlan]=useState<ActionPlan|null>(null),[tab,setTab]=useState<Tab>("goal"),[selected,setSelected]=useState<CareerRole|null>(null),[insights,setInsights]=useState<MarketInsights|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[alignmentVisible,setAlignmentVisible]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;Promise.all([getCareerRoles(),getCareerGoal()]).then(async([roleList,goalValue])=>{if(!active)return;setRoles(roleList);setGoal(goalValue);setTab(goalValue?"goal":"goal");const entries=await Promise.all(roleList.map(async role=>[role.id,await getCareerReadiness(role.id)] as const));if(active)setReadiness(Object.fromEntries(entries))}).catch(()=>active&&setError("Career mapping could not load. Make sure the backend is running and the career seed has been applied.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const choose=async(role:CareerRole)=>{setBusy(true);setError("");try{const value=await setCareerGoal(role.id,goal?.career_goal.job_ready_alert??false);setGoal(value);setReadiness(previous=>({...previous,[role.id]:value.readiness}));setSelected(null);setTab("goal");setPlan(null);setAlignmentVisible(true)}catch(reason){setError(reason instanceof Error?reason.message:"Could not save career goal.")}finally{setBusy(false)}};
 const view=async(role:CareerRole)=>{setSelected(role);setInsights(null);try{setInsights(await getCareerMarketInsights(role.id))}catch{setInsights(null)}};
 const loadPlan=async()=>{if(!goal)return;setBusy(true);setError("");try{setPlan(await getCareerActionPlan(goal.role.id))}catch(reason){setError(reason instanceof Error?reason.message:"Could not generate action plan.")}finally{setBusy(false)}};
 const toggleAlert=async()=>{if(!goal)return;setBusy(true);try{setGoal(await setCareerGoal(goal.role.id,!goal.career_goal.job_ready_alert,goal.career_goal.target_date??undefined))}catch(reason){setError(reason instanceof Error?reason.message:"Could not update alert.")}finally{setBusy(false)}};
 const remove=async()=>{if(!goal||!confirm("Remove this career goal?"))return;await deleteCareerGoal();setGoal(null);setPlan(null)};
 if(loading)return <div className="mx-auto max-w-7xl animate-pulse space-y-5"><div className="h-20 rounded-xl bg-slate-900"/><div className="grid gap-5 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-64 rounded-2xl bg-slate-900"/>)}</div></div>;
 const browser=<RoleSelector roles={roles} readiness={readiness} goalRoleId={goal?.role.id} onView={role=>void view(role)} onSelect={role=>void choose(role)}/>;
 return <div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-cyan-300">Career Skill Mapping</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Turn learning progress into career readiness</h1><p className="mt-2 max-w-3xl text-slate-400">Compare your live mastery profile with real role requirements and follow a prioritized path to close the gaps.</p></div>{goal&&<div className="rounded-xl border border-slate-800 bg-slate-900 px-4 py-3 text-sm"><span className="text-slate-500">Current target:</span> <b>{goal.role.title}</b><button onClick={()=>setTab("explore")} className="ml-3 text-cyan-300">Change</button></div>}</div>{error&&<p className="mt-5 rounded-xl border border-red-400/20 bg-red-400/5 p-4 text-red-200">{error}</p>}<div className="my-7 flex gap-1 overflow-x-auto border-b border-slate-800">{([['goal','My Career Map'],['explore','Explore Roles'],['compare','Compare Roles']] as const).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-bold ${tab===key?"border-cyan-400 text-cyan-300":"border-transparent text-slate-500"}`}>{label}</button>)}</div>
 {tab==="explore"&&browser}{tab==="compare"&&<RoleComparison roles={roles}/>} 
 {tab==="goal"&&(!goal?<><div className="mb-6 rounded-2xl border border-dashed border-slate-700 p-6 text-center"><h2 className="text-2xl font-bold">Choose your target career</h2><p className="mt-2 text-slate-400">Your readiness starts at 0% safely even if you have not completed an assessment yet.</p></div>{browser}</>:<div className="space-y-6">{alignmentVisible&&goal.roadmap_alignment&&goal.roadmap_alignment.missing_from_roadmap.length>0&&<div className="flex items-start justify-between gap-4 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm text-amber-100"><span>⚠ {goal.roadmap_alignment.suggestion}</span><button onClick={()=>setAlignmentVisible(false)} aria-label="Dismiss roadmap suggestion">✕</button></div>}<section className="rounded-2xl border border-cyan-400/20 bg-slate-900/60 p-6"><div className="grid items-center gap-6 lg:grid-cols-[300px_1fr]"><ReadinessMeterFromData readiness={goal.readiness}/><div><p className="text-xs font-bold uppercase text-cyan-300">Primary career goal</p><h2 className="mt-2 text-3xl font-black">{goal.role.title}</h2><p className="mt-2 capitalize text-slate-400">{goal.readiness.readiness_level.replaceAll("_"," ")} · {goal.readiness.estimated_weeks_to_ready??0} estimated weeks to job-ready</p><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>void loadPlan()} className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">{busy?"Generating...":plan?"Refresh Action Plan":"Generate Action Plan"}</button><button disabled={busy} onClick={()=>void toggleAlert()} className="rounded-xl border border-slate-700 px-4 py-3 text-sm">🔔 Job-Ready Alert: {goal.career_goal.job_ready_alert?"ON":"OFF"}</button><button onClick={()=>void remove()} className="rounded-xl px-4 py-3 text-sm text-red-300">Remove Goal</button></div>{goal.career_goal.job_ready_alert&&goal.readiness.overall_readiness_percentage>=85&&<p className="mt-4 rounded-lg bg-emerald-400/10 p-3 text-sm text-emerald-300">🎉 You reached the 85% job-ready threshold!</p>}</div></div></section><div className="grid gap-6 xl:grid-cols-[minmax(0,3fr)_minmax(320px,2fr)]"><section className="rounded-2xl border border-slate-800 bg-slate-900/40 p-5"><h2 className="mb-5 text-xl font-bold">Skill Gap Map</h2><SkillGapChart readiness={goal.readiness}/></section><aside className="xl:sticky xl:top-24 xl:self-start">{plan?<GapActionPlan plan={plan}/>:<div className="rounded-2xl border border-dashed border-slate-700 p-7 text-center"><h2 className="text-xl font-bold">Your personalized action plan</h2><p className="mt-2 text-sm text-slate-400">Generate a sequenced plan that starts with critical essentials and highlights quick wins.</p><button disabled={busy} onClick={()=>void loadPlan()} className="mt-5 rounded-xl bg-indigo-400 px-5 py-3 font-bold text-slate-950">Generate Plan</button></div>}</aside></div></div>)}
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 p-6"><button onClick={()=>setSelected(null)} className="float-right text-slate-400" aria-label="Close role details">✕</button><span className="rounded-full bg-indigo-400/10 px-3 py-1 text-xs uppercase text-indigo-300">{selected.category}</span><h2 className="mt-4 text-3xl font-black">{selected.title}</h2><p className="mt-3 leading-7 text-slate-300">{selected.description}</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="font-bold">Typical responsibilities</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-400">{selected.responsibilities.map(item=><li key={item}>{item}</li>)}</ul></div><div><h3 className="font-bold">Required skills</h3><ul className="mt-2 space-y-1 text-sm text-slate-400">{selected.skill_requirements.slice(0,8).map(item=><li key={item.skill_id}>{item.importance==="essential"?"●":"○"} {item.skill_name} · {item.min_mastery_percentage}%</li>)}</ul></div></div>{insights?<div className="mt-6 rounded-xl border border-slate-800 bg-slate-950/50 p-4"><h3 className="font-bold">General market insights</h3><p className="mt-2 text-sm text-slate-400">{insights.demand_description}</p><p className="mt-3 text-xs text-slate-500">{insights.disclaimer}</p></div>:<p className="mt-6 text-sm text-slate-500">Loading general market insights...</p>}<button disabled={busy} onClick={()=>void choose(selected)} className="mt-6 w-full rounded-xl bg-cyan-400 py-3 font-bold text-slate-950">Set as My Career Goal</button></div></div>}
 </div>}
