"use client";
import { useEffect, useRef, useState } from "react";
import { MarkdownContent } from "@/components/tutor/MessageBubble";
import { getMentorHistory, sendMentorMessage } from "@/lib/projects";
import type { TutorMessage } from "@/lib/tutor";

export function MentorChat({ userProjectId, stageId, focusToken = 0 }: { userProjectId: string; stageId: string; focusToken?: number }): JSX.Element {
  const [messages, setMessages] = useState<TutorMessage[]>([]); const [text, setText] = useState(""); const [sending, setSending] = useState(false); const [error, setError] = useState(""); const bottom = useRef<HTMLDivElement>(null); const input = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { let active = true; setError(""); getMentorHistory(userProjectId, stageId).then((items) => { if (active) setMessages(items); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Mentor history could not be loaded."); }); return () => { active = false; }; }, [userProjectId, stageId]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);
  useEffect(() => { if (focusToken > 0) input.current?.focus(); }, [focusToken]);
  const send = async (): Promise<void> => { const value = text.trim(); if (!value || sending) return; const optimistic: TutorMessage = { id: `local-${Date.now()}`, role: "user", content: value, metadata: {}, created_at: new Date().toISOString() }; setText(""); setError(""); setMessages((current) => [...current, optimistic]); setSending(true); try { const reply = await sendMentorMessage(userProjectId, stageId, value); setMessages((current) => [...current, { id: reply.assistant_message_id, role: "assistant", content: reply.content, metadata: { socratic_mode: true }, created_at: new Date().toISOString() }]); } catch (reason) { setError(reason instanceof Error ? reason.message : "The mentor could not respond. Your work is still safe."); } finally { setSending(false); } };
  return <section className="flex h-[640px] flex-col rounded-2xl border border-slate-800 bg-slate-900/70"><header className="border-b border-slate-800 p-4"><h2 className="font-bold text-sky-200">AI Project Mentor</h2><p className="text-xs text-slate-500">Socratic guidance for the current active stage</p></header><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((message) => <div key={message.id} className={`rounded-xl p-3 text-sm ${message.role === "user" ? "ml-8 bg-indigo-500 text-white" : "mr-4 border border-slate-800 bg-slate-950/60 text-slate-200"}`}>{message.role === "assistant" ? <MarkdownContent content={message.content} /> : <p className="whitespace-pre-wrap">{message.content}</p>}</div>)}{sending && <p className="text-xs text-slate-500">Mentor is thinking…</p>}<div ref={bottom} /></div><form onSubmit={(event) => { event.preventDefault(); void send(); }} className="border-t border-slate-800 p-3">{error && <p role="alert" className="mb-2 rounded-lg bg-red-400/10 p-2 text-xs text-red-200">{error}</p>}<textarea ref={input} value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} rows={3} placeholder="Ask your mentor about this stage…" className="w-full resize-none rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm outline-none focus:border-sky-400" /><button type="submit" disabled={sending || !text.trim()} className="mt-2 w-full rounded-lg bg-sky-400 px-3 py-2 text-sm font-bold text-slate-950 disabled:opacity-50">{sending ? "Sending…" : "Ask mentor"}</button></form></section>;
}
