"use client";
import { useState } from "react";
import { submitFinalProject } from "@/lib/projects";
import type { Completion } from "@/lib/projects";

export function ProjectSubmission({ userProjectId, onComplete }: { userProjectId: string; onComplete: (completion: Completion) => void }): JSX.Element {
  const [form, setForm] = useState({ project_description: "", final_code: "", reflection: "", challenges_faced: "", github_url: "" });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const update = (key: keyof typeof form, value: string): void => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (): Promise<void> => { setBusy(true); setError(""); try { onComplete(await submitFinalProject(userProjectId, { ...form, final_code: form.final_code || null, github_url: form.github_url || null })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Submission failed"); } finally { setBusy(false); } };
  const ready = form.project_description.trim().length >= 50 && form.reflection.trim().length >= 100 && form.challenges_faced.trim().length >= 50;
  return <section className="rounded-2xl border border-indigo-400/30 bg-indigo-400/5 p-6"><h2 className="text-2xl font-bold">Final project submission</h2><p className="mt-2 text-sm text-slate-400">All milestones are complete. Package your work and reflect on what you learned.</p><div className="mt-5 grid gap-4">{([['project_description','Project description (minimum 50 characters)'],['reflection','Reflection and learning (minimum 100 characters)'],['challenges_faced','Challenges you overcame (minimum 50 characters)']] as const).map(([key,label]) => <label key={key} className="text-sm font-semibold">{label}<textarea rows={4} value={form[key]} onChange={(event) => update(key,event.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-normal outline-none focus:border-sky-400" /></label>)}<label className="text-sm font-semibold">Final code (optional)<textarea rows={9} value={form.final_code} onChange={(event) => update("final_code",event.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-mono text-sm font-normal" /></label><label className="text-sm font-semibold">GitHub URL (optional)<input value={form.github_url} onChange={(event) => update("github_url",event.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 font-normal" /></label></div>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}<button type="button" onClick={() => void submit()} disabled={busy || !ready} className="mt-5 rounded-lg bg-indigo-400 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">{busy ? "Evaluating final project…" : "Submit final project"}</button></section>;
}
