"use client";
import Link from "next/link";
import type { ProjectLibraryItem } from "@/lib/projects";

export function ProjectCard({ project, onStart, starting = false }: { project: ProjectLibraryItem; onStart?: (id: string) => void; starting?: boolean }): JSX.Element {
  const active = project.user_status === "active"; const completed = project.user_status === "completed";
  const workspaceHref = project.user_project_id ? `/projects/workspace/${project.user_project_id}` : null;
  return <article className={`flex h-full flex-col rounded-2xl border p-5 ${active ? "border-sky-400/35 bg-sky-400/5" : completed ? "border-emerald-400/25 bg-emerald-400/5" : "border-slate-800 bg-slate-900/60"}`}><div className="flex items-center justify-between"><span className="rounded-full bg-indigo-400/10 px-2.5 py-1 text-[10px] font-bold uppercase text-indigo-200">{project.category.replaceAll("-", " ")}</span>{active && <span className="text-xs font-bold text-sky-300">In progress</span>}{completed && <span className="text-xs font-bold text-emerald-300">✓ Completed</span>}</div><h3 className="mt-4 text-xl font-bold">{project.title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-slate-400">{project.short_description}</p><p className="mt-4 text-sm text-amber-300" aria-label={`Difficulty ${project.difficulty_level} of 5`}>{"★".repeat(project.difficulty_level)}{"☆".repeat(5 - project.difficulty_level)}</p><p className="mt-2 text-xs text-slate-500">{project.estimated_hours} hours · {project.stages_count} stages</p><div className="mt-3 flex flex-wrap gap-1.5">{project.tech_stack.slice(0, 3).map((item) => <span key={item} className="rounded bg-slate-800 px-2 py-1 text-[10px] text-slate-300">{item}</span>)}</div>{active && <div className="mt-4"><div className="h-2 rounded bg-slate-800"><div className="h-full rounded bg-sky-400" style={{ width: `${project.user_progress_percentage}%` }} /></div><p className="mt-1 text-xs text-slate-500">{project.user_progress_percentage}% complete</p></div>}{!active && !completed && <p className={`mt-4 text-xs ${project.is_eligible ? "text-emerald-300" : "text-amber-300"}`}>{project.is_eligible ? "✓ You’re eligible" : `Needs: ${project.missing_prerequisites[0]?.skill_name ?? "prerequisites"}`}</p>}<div className="mt-5 flex gap-2">{workspaceHref ? <Link href={workspaceHref} className={`flex-1 rounded-lg px-3 py-2 text-center text-sm font-bold ${completed ? "border border-emerald-400/30 text-emerald-200" : "bg-sky-400 text-slate-950"}`}>{completed ? "View project →" : "Continue →"}</Link> : <Link href={`/projects/${project.id}`} className="flex-1 rounded-lg border border-slate-700 px-3 py-2 text-center text-sm font-semibold hover:bg-slate-800">View details</Link>}{!project.user_status && project.is_eligible && onStart && <button disabled={starting} onClick={() => onStart(project.id)} className="rounded-lg bg-sky-400 px-3 py-2 text-sm font-bold text-slate-950 disabled:opacity-60">{starting ? "Starting…" : "Start"}</button>}</div></article>;
}
