"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ExerciseCard } from "@/components/exercises/ExerciseCard";
import { ExerciseResults } from "@/components/exercises/ExerciseResults";
import { ApiError, apiGet, apiPatch, apiPost } from "@/lib/api";
import type { AttemptFeedback, CodeReview, Exercise } from "@/lib/exercises";
import type { ConversationDetail, SendMessageResponse } from "@/lib/tutor";

interface StoredSession { currentIndex: number; results: Array<AttemptFeedback | null>; answers: Record<string, string>; startedAt: number }

export function ExerciseSession({ exercises, skillId, skillName, skillSlug, initialMastery, planItemId, onPracticeMore }: { exercises: Exercise[]; skillId: string; skillName: string; skillSlug: string; initialMastery: number; planItemId?: string; onPracticeMore: () => void }): JSX.Element {
  const router = useRouter(); const storageKey = `exercise_session_${skillId}`;
  const [currentIndex, setCurrentIndex] = useState(0); const [results, setResults] = useState<Array<AttemptFeedback | null>>([]); const [answers, setAnswers] = useState<Record<string, string>>({});
  const [startedAt, setStartedAt] = useState(() => Date.now()); const [submitting, setSubmitting] = useState(false); const [hint, setHint] = useState<string | null>(null); const [hintIndex, setHintIndex] = useState(0);
  const [reviewing, setReviewing] = useState(false); const [review, setReview] = useState<CodeReview | null>(null); const [complete, setComplete] = useState(false); const [toast, setToast] = useState<string | null>(null);
  const exerciseStartedAt = useRef(Date.now()); const lastReviewAt = useRef(0); const planCompleted = useRef(false);
  useEffect(() => { const raw = sessionStorage.getItem(storageKey); if (!raw) return; try { const stored = JSON.parse(raw) as StoredSession; if (stored.currentIndex < exercises.length) { setCurrentIndex(stored.currentIndex); setResults(stored.results); setAnswers(stored.answers); setStartedAt(stored.startedAt); } } catch { sessionStorage.removeItem(storageKey); } }, [exercises.length, storageKey]);
  useEffect(() => { if (!complete) sessionStorage.setItem(storageKey, JSON.stringify({ currentIndex, results, answers, startedAt } satisfies StoredSession)); }, [answers, complete, currentIndex, results, startedAt, storageKey]);
  const exercise = exercises[currentIndex]; const answer = exercise ? answers[exercise.id] ?? (exercise.exercise_type === "coding" ? exercise.content.starter_code ?? "" : "") : ""; const feedback = results[currentIndex] ?? null;
  const updateAnswer = (value: string): void => setAnswers((current) => ({ ...current, [exercise.id]: value }));
  const submit = async (): Promise<void> => { if (!exercise || !answer.trim() || submitting) return; setSubmitting(true); setToast(null); try { const result = await apiPost<AttemptFeedback>(`/api/v1/exercises/${exercise.id}/attempt`, { user_answer: answer, time_spent_seconds: Math.max(0, Math.round((Date.now() - exerciseStartedAt.current) / 1000)) }); setResults((current) => { const next = [...current]; next[currentIndex] = result; return next; }); } catch (reason) { setToast(reason instanceof ApiError ? reason.message : "Your answer could not be reviewed. It remains in the editor."); } finally { setSubmitting(false); } };
  const next = async (): Promise<void> => { setHint(null); setHintIndex(0); setReview(null); exerciseStartedAt.current = Date.now(); if (currentIndex + 1 < exercises.length) { setCurrentIndex((value) => value + 1); return; } setComplete(true); sessionStorage.removeItem(storageKey); if (planItemId && !planCompleted.current) { planCompleted.current = true; try { await apiPatch(`/api/v1/plans/items/${planItemId}`, { status: "completed", time_spent_minutes: Math.max(1, Math.round((Date.now() - startedAt) / 60000)) }); } catch { setToast("The practice session is complete, but the daily-plan item could not be updated automatically."); } } };
  const skip = (): void => { setResults((current) => { const nextResults = [...current]; nextResults[currentIndex] = null; return nextResults; }); void next(); };
  const getHint = async (): Promise<void> => { if (!exercise) return; try { const response = await apiGet<{ hint: string }>(`/api/v1/exercises/${exercise.id}/hint?hint_index=${hintIndex}`); setHint(response.hint); setHintIndex((value) => value + 1); } catch (reason) { setToast(reason instanceof ApiError ? reason.message : "No more hints are available."); } };
  const runTests = async (): Promise<void> => { if (!exercise || reviewing) return; const now = Date.now(); if (now - lastReviewAt.current < 500) return; lastReviewAt.current = now; setReviewing(true); try { const [result] = await Promise.all([apiPost<CodeReview>("/api/v1/exercises/code-review", { code: answer, context: exercise.content.problem_statement, skill_id: skillId }), new Promise((resolve) => window.setTimeout(resolve, 1000))]); setReview(result); } catch (reason) { setToast(reason instanceof ApiError ? reason.message : "The simulated test review could not run."); } finally { setReviewing(false); } };
  const askTutor = async (): Promise<void> => { const failed = exercises.filter((_, index) => results[index] && !results[index]!.is_correct).map((item) => item.title); try { const conversation = await apiPost<ConversationDetail>("/api/v1/tutor/conversations", { skill_id: skillId }); await apiPost<SendMessageResponse>(`/api/v1/tutor/conversations/${conversation.id}/messages`, { content: `I just completed a ${skillName} exercise session and struggled with these topics: ${failed.join(", ")}. Can we go through them?`, socratic_mode: true }); router.push(`/tutor/${conversation.id}`); } catch { setToast("The tutor could not be opened. Your session results remain saved."); } };
  if (complete) return <><ExerciseResults skillName={skillName} skillSlug={skillSlug} exercises={exercises} results={results} durationMinutes={Math.max(1, Math.round((Date.now() - startedAt) / 60000))} initialMastery={initialMastery} onPracticeMore={onPracticeMore} onAskTutor={() => void askTutor()} />{toast && <Toast message={toast} onClose={() => setToast(null)} />}</>;
  if (!exercise) return <p>No exercises are available.</p>;
  const correctSoFar = results.filter((item) => item?.is_correct).length;
  return <div className="mx-auto max-w-5xl"><div className="mb-5"><div className="flex flex-wrap justify-between gap-3 text-sm"><span>Exercise {currentIndex + 1} of {exercises.length} · <b>{skillName}</b></span><span className="text-emerald-300">Score: {correctSoFar}/{results.filter(Boolean).length} ✓</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-sky-400 to-indigo-400 transition-all" style={{ width: `${(currentIndex + 1) / exercises.length * 100}%` }} /></div></div><ExerciseCard exercise={exercise} index={currentIndex} total={exercises.length} answer={answer} feedback={feedback} hint={hint} submitting={submitting} reviewing={reviewing} review={review} onAnswer={updateAnswer} onSubmit={() => void submit()} onSkip={skip} onHint={() => void getHint()} onNext={() => void next()} onRunTests={() => void runTests()} onError={setToast} />{toast && <Toast message={toast} onClose={() => setToast(null)} />}</div>;
}

function Toast({ message, onClose }: { message: string; onClose: () => void }): JSX.Element { return <div role="status" className="fixed bottom-5 right-5 z-[80] max-w-sm rounded-xl border border-slate-700 bg-slate-900 px-5 py-3 text-sm shadow-2xl">{message}<button type="button" onClick={onClose} className="ml-3 text-slate-500">×</button></div>; }
