"use client";

import { CodingExercise } from "@/components/exercises/CodingExercise";
import { DebuggingExercise, type DebuggingAnswer } from "@/components/exercises/DebuggingExercise";
import { ExplanationExercise } from "@/components/exercises/ExplanationExercise";
import { FeedbackPanel } from "@/components/exercises/FeedbackPanel";
import { MCQExercise } from "@/components/exercises/MCQExercise";
import { WeaknessAlert } from "@/components/exercises/WeaknessAlert";
import type { AttemptFeedback, CodeReview, Exercise } from "@/lib/exercises";

function parseDebugging(value: string, starter: string): DebuggingAnswer {
  const [description = "", code = starter] = value.split("\nFIXED CODE:\n", 2);
  return { description: description.replace(/^DESCRIPTION:\n/, ""), code };
}

export function ExerciseCard({ exercise, index, total, answer, feedback, hint, submitting, reviewing, review, onAnswer, onSubmit, onSkip, onHint, onNext, onRunTests, onError }: { exercise: Exercise; index: number; total: number; answer: string; feedback: AttemptFeedback | null; hint: string | null; submitting: boolean; reviewing: boolean; review: CodeReview | null; onAnswer: (answer: string) => void; onSubmit: () => void; onSkip: () => void; onHint: () => void; onNext: () => void; onRunTests: () => void; onError: (message: string) => void }): JSX.Element {
  const difficulty = "●".repeat(exercise.difficulty) + "○".repeat(5 - exercise.difficulty);
  const words = answer.trim() ? answer.trim().split(/\s+/).length : 0;
  const debugging = parseDebugging(answer, exercise.content.buggy_code ?? exercise.content.starter_code ?? "");
  const answerReady = exercise.exercise_type === "explanation" ? words >= 30 : exercise.exercise_type === "debugging" ? debugging.description.trim().length >= 5 && debugging.code.trim().length >= 10 : answer.trim().length > 0;
  return <article className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/60"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-sky-300">Exercise {index + 1} of {total}</p><h1 className="mt-2 text-xl font-bold">{exercise.title}</h1><p className="mt-1 text-xs capitalize text-slate-500">{exercise.exercise_type.replaceAll("_", " ")} · {exercise.skill_name}</p></div><span title={`Difficulty ${exercise.difficulty} of 5`} className="font-mono text-amber-300">{difficulty}</span></header><div className="p-5 sm:p-7">{exercise.exercise_type === "multiple_choice" && <MCQExercise exercise={exercise} value={answer} onChange={onAnswer} onSubmit={onSubmit} feedback={feedback} />}{exercise.exercise_type === "explanation" && <ExplanationExercise exercise={exercise} value={answer} onChange={onAnswer} disabled={Boolean(feedback)} />}{exercise.exercise_type === "debugging" && <DebuggingExercise exercise={exercise} value={debugging} onChange={(value) => onAnswer(`DESCRIPTION:\n${value.description}\nFIXED CODE:\n${value.code}`)} disabled={Boolean(feedback)} />}{exercise.exercise_type === "coding" && <CodingExercise exercise={exercise} value={answer || exercise.content.starter_code || ""} onChange={onAnswer} disabled={Boolean(feedback)} reviewing={reviewing} review={review} onRunTests={onRunTests} />}{hint && <div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm leading-6 text-amber-100">💡 {hint}</div>}{!feedback && <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><button type="button" disabled={!exercise.hints?.length} onClick={onHint} className="rounded-lg border border-slate-700 px-4 py-2 text-sm font-semibold disabled:opacity-40">💡 Hint</button><div className="flex gap-3"><button type="button" onClick={onSkip} className="px-3 py-2 text-sm text-slate-500">Skip</button><button type="button" disabled={!answerReady || submitting} onClick={onSubmit} className="rounded-lg bg-sky-400 px-5 py-2 text-sm font-bold text-slate-950 disabled:opacity-40">{submitting ? "Reviewing..." : "Submit Answer"}</button></div></div>}{feedback && <><FeedbackPanel exercise={exercise} feedback={feedback} onError={onError} />{feedback.weakness_detected && exercise.skill_id && exercise.skill_slug && <div className="mt-5"><WeaknessAlert skillId={exercise.skill_id} skillName={exercise.skill_name ?? "this skill"} skillSlug={exercise.skill_slug} pattern={feedback.weakness_detected} onError={onError} /></div>}<div className="mt-6 text-right"><button type="button" onClick={onNext} className="rounded-lg bg-sky-400 px-5 py-3 font-bold text-slate-950">{index + 1 === total ? "See Results →" : "Next Exercise →"}</button></div></>}</div></article>;
}
