"use client";

import Link from "next/link";
import type { ExerciseHistory, Recommendation } from "@/lib/exercises";
import type { LearnerContext } from "@/lib/tutor";

export function ExerciseHub({ recommendations, history, context }: { recommendations: Recommendation[]; history: ExerciseHistory[]; context: LearnerContext }): JSX.Element {
  const bySkill = [...recommendations].sort((a, b) => a.skill_mastery - b.skill_mastery);
  const masteryByName = new Map(context.skill_mastery.map((skill) => [skill.name, skill]));
  const skills = context.goal_skills.map((skill) => ({ ...skill, mastery: masteryByName.get(skill.name)?.mastery ?? 0, level: masteryByName.get(skill.name)?.level ?? "weak" }));
  return (
    <div className="mx-auto max-w-6xl">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-purple-300">Adaptive Practice</p><h1 className="mt-2 text-4xl font-black">Exercise Engine</h1><p className="mt-3 max-w-2xl leading-7 text-slate-400">Target weak areas with practice that adapts as your mastery changes.</p></div><Link href="/tutor" className="text-sm font-semibold text-sky-300">Ask your tutor for guidance →</Link></div>
      {bySkill.length > 0 && <section className="mt-8"><h2 className="text-xl font-bold text-amber-200">⚠ Areas Needing Practice</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{bySkill.slice(0, 3).map((item) => <article key={item.skill_slug} className="rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5"><p className="font-bold">{item.skill_name}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-amber-400" style={{ width: `${item.skill_mastery * 100}%` }} /></div><p className="mt-2 text-xs text-slate-500">Mastery: {Math.round(item.skill_mastery * 100)}%</p><Link href={`/exercises/practice/${item.skill_slug}`} className="mt-4 inline-block text-sm font-bold text-amber-300">Practice Now →</Link></article>)}</div></section>}
      <section className="mt-9"><h2 className="text-xl font-bold">Recommended For You</h2>{recommendations.length === 0 ? <div className="mt-4 rounded-2xl border border-slate-800 bg-slate-900/50 p-7 text-slate-400">Complete an assessment to unlock weakness-targeted recommendations.</div> : <div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{recommendations.slice(0, 4).map((item) => <Link href={`/exercises/practice/${item.skill_slug}`} key={item.exercise.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 transition hover:-translate-y-1 hover:border-purple-400/40"><span className="rounded-full bg-purple-400/10 px-2 py-1 text-[10px] font-bold uppercase text-purple-300">{item.exercise.exercise_type.replaceAll("_", " ")}</span><h3 className="mt-4 font-bold leading-6">{item.exercise.title}</h3><p className="mt-3 text-xs leading-5 text-slate-500">{item.reason}</p><p className="mt-4 font-mono text-xs text-amber-300">{"●".repeat(item.exercise.difficulty)}{"○".repeat(5 - item.exercise.difficulty)}</p></Link>)}</div>}</section>
      <section className="mt-9"><h2 className="text-xl font-bold">Practice by Skill</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{skills.map((skill) => <article key={skill.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-bold">{skill.name}</h3><span className="text-xs capitalize text-slate-500">{skill.level}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${skill.mastery < .4 ? "bg-red-400" : skill.mastery < .6 ? "bg-amber-400" : skill.mastery < .8 ? "bg-sky-400" : "bg-emerald-400"}`} style={{ width: `${skill.mastery * 100}%` }} /></div><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-500">{Math.round(skill.mastery * 100)}% mastery</span><Link href={`/exercises/practice/${skill.slug}`} className="text-sm font-bold text-sky-300">Practice →</Link></div></article>)}</div></section>
      <section className="mt-9"><h2 className="text-xl font-bold">Recent Performance</h2>{history.length === 0 ? <p className="mt-4 rounded-2xl border border-slate-800 bg-slate-900/50 p-6 text-slate-500">Your completed and attempted exercises will appear here.</p> : <div className="mt-4 overflow-hidden rounded-2xl border border-slate-800">{history.slice(0, 8).map((item) => <div key={item.exercise_id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 bg-slate-900/60 px-5 py-4 last:border-0"><div><p className="font-semibold">{item.is_completed ? "✅" : "↻"} {item.exercise_title}</p><p className="mt-1 text-xs text-slate-500">{item.skill_name ?? "General"} · {item.exercise_type.replaceAll("_", " ")} · {item.attempts} attempt{item.attempts === 1 ? "" : "s"}</p></div><span className="text-sm font-bold text-sky-300">Best {Math.round(item.best_score * 100)}%</span></div>)}</div>}</section>
    </div>
  );
}
