"use client";

import Link from "next/link";
import { useEffect } from "react";
import type { PlanSummary } from "@/lib/plans";

const colors = ["#38bdf8", "#a78bfa", "#34d399", "#facc15", "#fb923c", "#f87171"];

export function CompletionCelebration({ name, summary, onClose }: { name: string; summary: PlanSummary; onClose: () => void }): JSX.Element {
  useEffect(() => { const timer = window.setTimeout(onClose, 8000); return () => window.clearTimeout(timer); }, [onClose]);
  return <div role="dialog" aria-modal="true" onClick={onClose} className="fixed inset-0 z-[70] flex items-center justify-center overflow-hidden bg-slate-950/95 p-4 text-slate-100"><div aria-hidden="true" className="pointer-events-none absolute inset-0">{Array.from({ length: 50 }, (_, index) => <i key={index} className="absolute top-[-20px] h-3 w-2 animate-confetti" style={{ left: `${(index * 37) % 100}%`, backgroundColor: colors[index % colors.length], animationDelay: `${(index % 20) / 10}s`, animationDuration: `${2.8 + (index % 7) / 4}s`, "--drift": `${((index % 9) - 4) * 22}px` } as React.CSSProperties} />)}</div><div onClick={(event) => event.stopPropagation()} className="relative w-full max-w-3xl text-center"><svg viewBox="0 0 100 100" className="mx-auto h-28 w-28"><circle cx="50" cy="50" r="44" fill="none" stroke="#34d399" strokeWidth="5" className="animate-check-circle" /><path d="m28 51 14 14 31-34" fill="none" stroke="#34d399" strokeWidth="7" strokeLinecap="round" strokeLinejoin="round" className="animate-check-path" /></svg><h1 className="mt-5 animate-celebration-in text-4xl font-black sm:text-5xl">Plan Complete! 🎉</h1><p className="mt-3 text-xl text-slate-300">You crushed it today, {name}!</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{[[`${summary.completed_items}/${summary.total_items}`, "Tasks"], [`${summary.actual_minutes_spent}m`, "Studied"], [`+${summary.xp_earned} XP`, "Earned"], [`🔥 ${summary.streak_days}`, "Days"]].map(([value, label], index) => <div key={label} className="animate-celebration-in rounded-xl border border-slate-800 bg-slate-900/80 p-4" style={{ animationDelay: `${0.4 + index * 0.15}s` }}><b className="text-xl">{value}</b><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</div>{summary.skills_practiced.length > 0 && <div className="mt-6"><p className="text-sm text-slate-500">Skills practiced today</p><div className="mt-2 flex flex-wrap justify-center gap-2">{summary.skills_practiced.map((skill) => <span key={skill} className="rounded-full bg-indigo-400/10 px-3 py-1 text-sm text-indigo-200">{skill}</span>)}</div></div>}<p className="mt-6 text-sm text-sky-300">Roadmap progress: +{summary.roadmap_progress_delta}%</p><div className="mt-7 flex flex-wrap justify-center gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-slate-700 px-5 py-3 font-bold">See Tomorrow&apos;s Preview</button><Link href="/dashboard" className="rounded-xl bg-sky-400 px-5 py-3 font-bold text-slate-950">Go to Dashboard</Link></div><p className="mt-5 text-xs text-slate-600">This celebration closes automatically.</p></div></div>;
}
