"""add project learning tables

Revision ID: e7d3a9b421ce
Revises: c4a9d81e2f10
"""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str="e7d3a9b421ce"; down_revision: str|None="c4a9d81e2f10"; branch_labels: str|Sequence[str]|None=None; depends_on: str|Sequence[str]|None=None

def upgrade()->None:
    op.create_table("projects",sa.Column("title",sa.String(300),nullable=False),sa.Column("slug",sa.String(300),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("short_description",sa.String(500),nullable=False),sa.Column("difficulty_level",sa.Integer(),nullable=False),sa.Column("estimated_hours",sa.Float(),nullable=False),sa.Column("category",sa.String(100),nullable=False),sa.Column("required_skills",sa.JSON(),nullable=False),sa.Column("prerequisite_skills",sa.JSON(),nullable=False),sa.Column("tech_stack",sa.JSON(),nullable=False),sa.Column("learning_outcomes",sa.JSON(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("is_featured",sa.Boolean(),nullable=False),sa.Column("order_index",sa.Integer(),nullable=False),sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("slug")); op.create_index("ix_projects_slug","projects",["slug"],unique=True); op.create_index("ix_projects_category","projects",["category"])
    op.create_table("project_stages",sa.Column("project_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("order_index",sa.Integer(),nullable=False),sa.Column("stage_type",sa.String(50),nullable=False),sa.Column("instructions",sa.Text(),nullable=False),sa.Column("deliverables",sa.JSON(),nullable=False),sa.Column("hints",sa.JSON(),nullable=False),sa.Column("resources",sa.JSON(),nullable=False),sa.Column("estimated_minutes",sa.Integer(),nullable=False),sa.Column("validation_criteria",sa.JSON(),nullable=False),sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["project_id"],["projects.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("project_id","order_index",name="uq_project_stage_order")); op.create_index("ix_project_stages_project_id","project_stages",["project_id"])
    op.create_table("user_projects",sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("project_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("status",sa.String(50),nullable=False),sa.Column("current_stage_index",sa.Integer(),nullable=False),sa.Column("total_stages",sa.Integer(),nullable=False),sa.Column("work_data",sa.JSON(),nullable=False),sa.Column("xp_earned",sa.Integer(),nullable=False),sa.Column("final_submission_id",postgresql.UUID(as_uuid=True),nullable=True),sa.Column("started_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True),nullable=True),sa.Column("last_active_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["project_id"],["projects.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("user_id","project_id",name="uq_user_project")); op.create_index("ix_user_projects_user_id","user_projects",["user_id"]); op.create_index("ix_user_projects_project_id","user_projects",["project_id"])
    op.create_table("user_project_stages",sa.Column("user_project_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("stage_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("stage_order_index",sa.Integer(),nullable=False),sa.Column("status",sa.String(50),nullable=False),sa.Column("submitted_code",sa.Text()),sa.Column("submitted_notes",sa.Text()),sa.Column("submitted_reflection",sa.Text()),sa.Column("submission_hash",sa.String(64)),sa.Column("ai_feedback",sa.JSON()),sa.Column("ai_score",sa.Float()),sa.Column("criteria_met",sa.JSON()),sa.Column("hints_used",sa.Integer(),nullable=False),sa.Column("mentor_conversation_id",postgresql.UUID(as_uuid=True)),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["mentor_conversation_id"],["tutor_conversations.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["stage_id"],["project_stages.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_project_id"],["user_projects.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("user_project_id","stage_id",name="uq_user_project_stage")); op.create_index("ix_user_project_stages_user_project_id","user_project_stages",["user_project_id"])
    op.create_table("project_submissions",sa.Column("user_project_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("project_description",sa.Text(),nullable=False),sa.Column("final_code",sa.Text()),sa.Column("github_url",sa.String(500)),sa.Column("reflection",sa.Text()),sa.Column("challenges_faced",sa.Text()),sa.Column("overall_score",sa.Float()),sa.Column("evaluation_status",sa.String(50),nullable=False),sa.Column("ai_evaluation",sa.JSON()),sa.Column("xp_awarded",sa.Integer(),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("evaluated_at",sa.DateTime(timezone=True)),sa.Column("id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_project_id"],["user_projects.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id")); op.create_index("ix_project_submissions_user_id","project_submissions",["user_id"]); op.create_index("ix_project_submissions_user_project_id","project_submissions",["user_project_id"])
    op.create_foreign_key("fk_user_project_final_submission","user_projects","project_submissions",["final_submission_id"],["id"],ondelete="SET NULL")

def downgrade()->None:
    op.drop_constraint("fk_user_project_final_submission","user_projects",type_="foreignkey"); op.drop_index("ix_project_submissions_user_project_id",table_name="project_submissions"); op.drop_index("ix_project_submissions_user_id",table_name="project_submissions"); op.drop_table("project_submissions"); op.drop_index("ix_user_project_stages_user_project_id",table_name="user_project_stages"); op.drop_table("user_project_stages"); op.drop_index("ix_user_projects_project_id",table_name="user_projects"); op.drop_index("ix_user_projects_user_id",table_name="user_projects"); op.drop_table("user_projects"); op.drop_index("ix_project_stages_project_id",table_name="project_stages"); op.drop_table("project_stages"); op.drop_index("ix_projects_category",table_name="projects"); op.drop_index("ix_projects_slug",table_name="projects"); op.drop_table("projects")
