"""Idempotently seed curated career roles and skill requirements."""
from sqlalchemy import create_engine,select
from sqlalchemy.orm import Session
from app.core.config import settings
from app.models.career import CareerRole,CareerSkillRequirement
from app.models.skill import Skill

def req(slug:str,importance:str,minimum:float,target:float)->tuple[str,str,float,float]:return slug,importance,minimum,target
ROLES=[
{"title":"Machine Learning Engineer","slug":"ml-engineer","category":"ml-ai","seniority_level":"mid","average_salary_usd":145000,"demand_level":"very-high","short_description":"Builds, trains, and deploys ML models in production systems","typical_companies":["Google","Meta","Netflix","Startups","Consulting"],"responsibilities":["Design and implement ML pipelines","Train and evaluate machine learning models","Deploy models with monitoring","Collaborate with data and product teams","Optimize model scalability"],"related_role_slugs":["data-scientist","ai-engineer","mlops-engineer"],"requirements":[req("python-fundamentals","essential",.85,.95),req("python-oop","essential",.75,.85),req("numpy","essential",.75,.85),req("pandas","essential",.75,.85),req("statistics-fundamentals","essential",.70,.80),req("linear-algebra","essential",.65,.80),req("ml-fundamentals","essential",.80,.90),req("supervised-learning","essential",.80,.90),req("unsupervised-learning","important",.65,.80),req("model-evaluation","essential",.75,.85),req("feature-engineering","essential",.70,.85),req("deep-learning-fundamentals","important",.65,.80),req("fastapi","important",.60,.75),req("docker","important",.60,.75),req("mlops-fundamentals","important",.60,.75),req("sql-fundamentals","beneficial",.50,.65)]},
{"title":"Data Scientist","slug":"data-scientist","category":"data-science","seniority_level":"mid","average_salary_usd":130000,"demand_level":"very-high","short_description":"Extracts insights from complex data using statistics and ML","typical_companies":["Technology companies","Finance","Healthcare","Consulting"],"responsibilities":["Explore complex datasets","Build predictive models","Design experiments","Communicate insights"],"related_role_slugs":["ml-engineer","data-analyst","ml-research-scientist"],"requirements":[req("python-fundamentals","essential",.80,.90),req("pandas","essential",.80,.90),req("numpy","essential",.75,.85),req("statistics-fundamentals","essential",.80,.90),req("probability-theory","essential",.70,.85),req("data-visualization","essential",.75,.85),req("exploratory-data-analysis","essential",.80,.90),req("ml-fundamentals","important",.65,.80),req("supervised-learning","important",.65,.80),req("sql-fundamentals","essential",.70,.85),req("feature-engineering","important",.60,.75),req("linear-algebra","beneficial",.50,.65),req("model-evaluation","important",.65,.80)]},
{"title":"AI Engineer","slug":"ai-engineer","category":"ml-ai","seniority_level":"mid","average_salary_usd":160000,"demand_level":"very-high","short_description":"Builds AI-powered applications and systems using LLMs and agents","typical_companies":["AI labs","SaaS companies","Startups","Enterprise technology"],"responsibilities":["Build LLM applications","Design agent workflows","Deploy AI services","Evaluate AI quality and safety"],"related_role_slugs":["ml-engineer","nlp-engineer","mlops-engineer"],"requirements":[req("python-fundamentals","essential",.85,.95),req("python-oop","essential",.80,.90),req("ml-fundamentals","essential",.70,.85),req("deep-learning-fundamentals","essential",.70,.85),req("llms-generative-ai","essential",.80,.90),req("agentic-ai","essential",.75,.90),req("fastapi","essential",.75,.85),req("docker","essential",.70,.80),req("statistics-fundamentals","important",.60,.75),req("numpy","important",.65,.80),req("cloud-basics","important",.60,.75),req("mlops-fundamentals","important",.60,.75),req("sql-fundamentals","beneficial",.45,.60)]},
{"title":"Data Analyst","slug":"data-analyst","category":"data-science","seniority_level":"junior","average_salary_usd":85000,"demand_level":"high","short_description":"Analyzes business data to support decision-making","typical_companies":["Retail","Finance","Consulting","Technology companies"],"responsibilities":["Query and clean data","Build dashboards","Track business metrics","Present recommendations"],"related_role_slugs":["data-scientist"],"requirements":[req("python-fundamentals","important",.65,.80),req("pandas","essential",.75,.85),req("data-visualization","essential",.80,.90),req("sql-fundamentals","essential",.80,.90),req("statistics-fundamentals","essential",.70,.85),req("exploratory-data-analysis","essential",.75,.85),req("numpy","beneficial",.50,.65),req("probability-theory","beneficial",.50,.65)]},
{"title":"MLOps Engineer","slug":"mlops-engineer","category":"devops","seniority_level":"mid","average_salary_usd":150000,"demand_level":"high","short_description":"Builds infrastructure for deploying and monitoring ML systems at scale","typical_companies":["Cloud providers","Technology companies","Fintech","AI platforms"],"responsibilities":["Automate ML delivery","Operate model infrastructure","Monitor models","Improve reliability"],"related_role_slugs":["ml-engineer","ai-engineer"],"requirements":[req("python-fundamentals","essential",.80,.90),req("ml-fundamentals","essential",.70,.80),req("docker","essential",.85,.95),req("mlops-fundamentals","essential",.85,.95),req("cloud-basics","essential",.75,.85),req("fastapi","essential",.70,.85),req("model-evaluation","essential",.70,.80),req("python-oop","important",.65,.80),req("sql-fundamentals","important",.60,.75),req("statistics-fundamentals","beneficial",.50,.65)]},
{"title":"NLP Engineer","slug":"nlp-engineer","category":"ml-ai","seniority_level":"mid","average_salary_usd":155000,"demand_level":"very-high","short_description":"Specializes in natural language processing and text-based AI systems","typical_companies":["AI labs","Search companies","Enterprise software","Startups"],"responsibilities":["Build NLP pipelines","Train text models","Evaluate language systems","Deploy NLP services"],"related_role_slugs":["ai-engineer","ml-engineer","ml-research-scientist"],"requirements":[req("python-fundamentals","essential",.85,.95),req("python-oop","essential",.75,.85),req("ml-fundamentals","essential",.75,.85),req("deep-learning-fundamentals","essential",.75,.85),req("nlp-fundamentals","essential",.85,.95),req("llms-generative-ai","essential",.80,.90),req("neural-networks","essential",.75,.85),req("statistics-fundamentals","essential",.70,.80),req("numpy","important",.65,.80),req("linear-algebra","important",.65,.80),req("fastapi","beneficial",.55,.70),req("docker","beneficial",.50,.65)]},
{"title":"Research Scientist (ML)","slug":"ml-research-scientist","category":"research","seniority_level":"senior","average_salary_usd":200000,"demand_level":"medium","short_description":"Advances the state of the art in ML through novel research","typical_companies":["Research labs","Universities","Frontier AI companies","Big Tech"],"responsibilities":["Design novel methods","Run rigorous experiments","Publish research","Mentor research teams"],"related_role_slugs":["ml-engineer","data-scientist","nlp-engineer"],"requirements":[req("python-fundamentals","essential",.85,.95),req("statistics-fundamentals","essential",.90,.98),req("probability-theory","essential",.85,.95),req("linear-algebra","essential",.85,.95),req("calculus-for-ml","essential",.80,.92),req("ml-fundamentals","essential",.90,.98),req("supervised-learning","essential",.85,.95),req("deep-learning-fundamentals","essential",.85,.95),req("neural-networks","essential",.85,.95),req("numpy","essential",.80,.90),req("model-evaluation","essential",.80,.90),req("nlp-fundamentals","important",.70,.85)]}
]

def seed_careers()->None:
    engine=create_engine(settings.database_url.replace("+asyncpg","+psycopg2"),pool_pre_ping=True);roles_created=requirements_created=0
    with Session(engine) as session:
        skills={item.slug:item for item in session.scalars(select(Skill)).all()};existing={item.slug:item for item in session.scalars(select(CareerRole)).all()}
        for index,source in enumerate(ROLES):
            data=dict(source);requirements=list(data.pop("requirements"));data["description"]=data["short_description"]+". This curated role profile maps practical responsibilities to measurable platform skills.";data["is_featured"]=index<3;data["order_index"]=index
            role=existing.get(str(data["slug"]));
            if role is None:role=CareerRole(**data);session.add(role);session.flush();roles_created+=1
            else:
                for key,value in data.items():setattr(role,key,value)
            current={item.skill_id:item for item in role.skill_requirements}
            for order,(slug,importance,minimum,target) in enumerate(requirements):
                skill=skills.get(slug)
                if not skill:raise RuntimeError(f"Missing seeded skill: {slug}")
                item=current.get(skill.id)
                note=f"{skill.name} is {importance} for day-to-day success as a {role.title}."
                if item is None:session.add(CareerSkillRequirement(career_role_id=role.id,skill_id=skill.id,importance=importance,min_mastery_required=minimum,target_mastery=target,relevance_note=note,order_index=order));requirements_created+=1
                else:item.importance=importance;item.min_mastery_required=minimum;item.target_mastery=target;item.relevance_note=note;item.order_index=order
        session.commit()
    engine.dispose();print(f"Seeded {roles_created} career roles and {requirements_created} skill requirements")
if __name__=="__main__":seed_careers()
