"use client";
import type { TimeDistribution, XPHistoryDay } from "@/lib/progress";
import { useChartSize } from "./useChartSize";

export function ActivityAnalytics({ xp, time }: { xp: XPHistoryDay[]; time: TimeDistribution }): JSX.Element {
  const { ref, width }=useChartSize(); const h=220; const max=Math.max(1,...xp.map(d=>d.xp_earned)); const bar=Math.max(2,(width-36)/Math.max(1,xp.length)-2);
  const grid=new Map(time.grid.map(v=>[`${v.day}-${v.hour}`,v.minutes])); const maxMin=Math.max(1,...time.grid.map(v=>v.minutes)); const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
  return <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><p className="text-xs font-bold uppercase tracking-wider text-amber-300">XP earned</p><h2 className="mt-2 text-xl font-bold">Last 30 days</h2><div ref={ref} className="mt-5 min-h-[220px]">{width>0&&<svg width={width} height={h} role="img" aria-label="Daily XP bar chart"><line x1="30" x2={width} y1={h-24} y2={h-24} stroke="#334155"/>{xp.map((d,i)=>{const bh=(d.xp_earned/max)*(h-50); return <rect key={d.date} x={32+i*(bar+2)} y={h-24-bh} width={bar} height={bh} rx="2" fill="#fbbf24"><title>{d.date}: {d.xp_earned} XP</title></rect>})}</svg>}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">Study rhythm</p><h2 className="mt-2 text-xl font-bold">Time distribution</h2><p className="mt-1 text-sm text-slate-500">Peak: {time.peak_study_day} at {String(time.peak_study_hour).padStart(2,"0")}:00 · Avg {Math.round(time.average_session_minutes)} min/session</p><div className="mt-5 overflow-x-auto"><div className="min-w-[570px]">{days.map(day=><div key={day} className="mb-1 flex items-center gap-1"><span className="w-20 truncate text-[10px] text-slate-500">{day.slice(0,3)}</span>{Array.from({length:24},(_,hour)=>{const minutes=grid.get(`${day}-${hour}`)??0;return <i key={hour} className="h-4 flex-1 rounded-sm bg-sky-400" style={{opacity:minutes?Math.max(.18,minutes/maxMin):.04}} title={`${day} ${hour}:00 · ${minutes} min`}/>})}</div>)}</div></div></section></div>;
}
