"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import type { SkillBreakdownItem } from "@/lib/progress";

type SortKey = "skill_name" | "mastery_percentage" | "times_practiced" | "last_practiced_days_ago" | "mastery_7d_change";
export function SkillBreakdown({ skills }: { skills: SkillBreakdownItem[] }): JSX.Element {
  const [sort, setSort] = useState<SortKey>("mastery_percentage"); const [ascending, setAscending] = useState(false);
  const rows = useMemo(() => [...skills].sort((left, right) => { const a = left[sort], b = right[sort]; const comparison = typeof a === "string" ? String(a).localeCompare(String(b)) : Number(a ?? Number.MAX_SAFE_INTEGER) - Number(b ?? Number.MAX_SAFE_INTEGER); return ascending ? comparison : -comparison; }), [ascending, skills, sort]);
  const choose = (key: SortKey): void => { if (key === sort) setAscending(value => !value); else { setSort(key); setAscending(false); } };
  const header = (label: string, key: SortKey) => <button type="button" onClick={() => choose(key)} className="font-bold uppercase">{label}{sort === key ? ascending ? " ↑" : " ↓" : ""}</button>;
  return <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/60"><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-sky-300">Skill details</p><h2 className="mt-2 text-xl font-bold">Mastery breakdown</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-slate-950/70 text-xs text-slate-500"><tr><th className="px-5 py-3">{header("Skill", "skill_name")}</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">{header("Mastery", "mastery_percentage")}</th><th className="px-5 py-3">{header("Practiced", "times_practiced")}</th><th className="px-5 py-3">{header("Last", "last_practiced_days_ago")}</th><th className="px-5 py-3">{header("Trend", "mastery_7d_change")}</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-slate-800">{rows.map(skill => <tr key={skill.skill_id} className="group hover:bg-slate-800/40"><td className="px-5 py-4"><p className="font-semibold">{skill.skill_name}</p><p className="text-xs text-slate-500">{skill.mastery_level}</p></td><td className="px-5 py-4 capitalize text-slate-400">{skill.category.replaceAll("-", " ")}</td><td className="px-5 py-4"><div className="flex items-center gap-2"><div className="h-1.5 w-20 rounded bg-slate-800"><div className={`h-full rounded ${skill.mastery_percentage >= 80 ? "bg-emerald-400" : skill.mastery_percentage >= 50 ? "bg-sky-400" : skill.mastery_percentage >= 30 ? "bg-amber-400" : "bg-red-400"}`} style={{ width: `${skill.mastery_percentage}%` }} /></div>{skill.mastery_percentage}%</div></td><td className="px-5 py-4">{skill.times_practiced}×</td><td className="px-5 py-4 text-slate-400">{skill.last_practiced_days_ago === null ? "Never" : skill.last_practiced_days_ago === 0 ? "Today" : `${skill.last_practiced_days_ago}d ago`}</td><td className="px-5 py-4"><span className={skill.mastery_trend === "up" ? "text-emerald-300" : skill.mastery_trend === "down" ? "text-red-300" : "text-slate-400"}>{skill.mastery_trend === "up" ? "↗" : skill.mastery_trend === "down" ? "↘" : "→"} {skill.mastery_7d_change > 0 ? "+" : ""}{Math.round(skill.mastery_7d_change * 100)}%</span>{skill.review_due && <span className="ml-2 rounded bg-amber-400/10 px-2 py-1 text-xs text-amber-300">Review Due</span>}</td><td className="px-5 py-4"><Link className="font-semibold text-sky-300 opacity-70 group-hover:opacity-100" href={`/exercises/practice/${skill.skill_slug}`}>Practice →</Link></td></tr>)}</tbody></table></div></section>;
}
