export interface ProgressSummary { total_skills_tracked: number; skills_mastered: number; skills_in_progress: number; skills_not_started: number; average_mastery: number; strongest_skill: { name: string; mastery: number } | null; weakest_skill: { name: string; mastery: number } | null; total_study_minutes: number; total_exercises_completed: number; total_assessments_completed: number; roadmap_progress: number; days_learning: number; active_days: number; current_streak: number; longest_streak: number }
export interface MasteryPoint { date: string; skill_id: string | null; skill_name: string | null; mastery_score: number; mastery_percentage: number }
export interface LearningVelocity { mastery_gained_this_period: number; mastery_per_active_day: number; active_days_this_period: number; exercises_per_day: number; minutes_per_day: number; velocity_trend: "increasing" | "stable" | "decreasing"; velocity_vs_last_period: number; estimated_goal_completion_weeks: number | null }
export interface CategoryBreakdown { category: string; average_mastery: number; mastery_percentage: number; skills_count: number; skills_mastered: number; skills: Array<{ name: string; mastery: number }> }
export interface HeatmapDay { date: string; completed_items: number; study_minutes: number; intensity: number }
export interface SkillBreakdownItem { skill_id: string; skill_name: string; skill_slug: string; category: string; mastery_score: number; mastery_percentage: number; mastery_level: string; times_practiced: number; times_correct: number; accuracy_rate: number; last_practiced_days_ago: number | null; mastery_7d_change: number; mastery_trend: "up" | "down" | "stable" | "new"; review_due: boolean }
export interface TimeDistribution { by_hour: Array<{ hour: number; minutes: number }>; by_day_of_week: Array<{ day: string; minutes: number }>; peak_study_hour: number; peak_study_day: string; morning_learner: boolean; average_session_minutes: number; longest_session_minutes: number; grid: Array<{ day: string; hour: number; minutes: number }> }
export interface XPEvent { event_type: string; xp_earned: number; description: string | null; created_at: string }
export interface XPSummary { level: number; total_xp: number; xp_for_current_level: number; xp_for_next_level: number; xp_progress: number; xp_needed: number; progress_percentage: number; level_title: string; xp_breakdown: Record<string, number>; recent_xp_events: XPEvent[] }
export interface XPHistoryDay { date: string; xp_earned: number; events_count: number }
export interface Achievement { id: string; name: string; description: string; icon: string; achievement_type: string; xp_reward: number; earned_at: string | null; progress: number | null; progress_label: string | null }
export interface Achievements { earned: Achievement[]; locked: Achievement[]; total_earned: number; total_available: number; completion_percentage: number }
export interface StreakInfo { current_streak: number; longest_streak: number; streak_start_date: string | null; last_activity_date: string | null; streak_at_risk: boolean; streak_frozen: boolean; milestone_next: number; days_to_milestone: number }
export interface LeaderboardEntry { rank: number; user_name: string; level: number; total_xp: number; streak: number; is_current_user: boolean }
